version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../config/nginx:/etc/nginx
      - ../certs:/etc/ssl/private
    
networks:
  proxy:
    external: true
